
name: Luacheck
on: [push, pull_request]

jobs:
  luacheck:
    runs-on: docker
    container:
      image: akorn/luarocks:lua5.1-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Luacheck Linter
        run: |
          luarocks install luacheck
          luacheck .
